---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kong-service
  name: kong-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: ssl-proxy
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
    - name: ssl-admin
      port: 8444
      targetPort: 8444
  selector:
    app: kong
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:latest
        #          resources:
#            limits:
#              cpu: 1
#              memory: 400Mi
#            requests:
#              cpu: 200m
#              memory: 100Mi
        envFrom:
          - configMapRef:
              name: kong-config
        ports:
          - name: proxy
            containerPort: 8000
          - name: ssl-proxy
            containerPort: 8443
          - name: admin
            containerPort: 8001
          - name: ssl-admin
            containerPort: 8444
    #    livenessProbe:
    #      httpGet:
    #        path: /ambassador/v0/check_alive
    #        port: 8877
    #      initialDelaySeconds: 30
    #      periodSeconds: 3
    #    readinessProbe:
    #      httpGet:
    #        path: /ambassador/v0/check_ready
    #        port: 8877
    #      initialDelaySeconds: 30
    #      periodSeconds: 3
      restartPolicy: Always
