apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: yunfhu
data:
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_ADMIN_LISTEN: '0.0.0.0:8001'
  KONG_CASSANDRA_CONTACT_POINTS: kong-db
  KONG_DATABASE: cassandra
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-db
  KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr