#!/usr/bin/env python

import os
import sys

__author__ = 'yunfhu'
ws = "/root/rebuild_jars/"
# rebuilt jars manifest which placed under ws
jm = "jars.manifest"
# backup directory which placed under ws
bk = "backup/"
# the findPath of jars which need be replaced
fp = "/opt/"


def find(p):
    def fd(n):
        c = "find %s -name %s" % (p, n)
        r = [x.strip() for x in os.popen(c).readlines()]
        return r

    return fd


def copy(sw="", dw=""):
    def cp(n, d):
        c = "cp -rf %s %s" % (sw + n, dw + d)
        rs = os.system(c)
        if rs == 0:
             print("exec:%s succeed!" % c)
        else:
            print("exec:%s failed!" % c)

    return cp


def update(manifest):
    f = find(fp)
    u = copy(sw=ws)
    b = copy(dw=ws + bk)
    for jar in manifest:
        res = f(jar)
        for des in res:
            b(des, jar)
            u(jar, des)

def revert(manifest):
    f = find(fp)
    r = copy(sw=ws+bk)
    for jar in manifest:
        res = f(jar)
        for des in res:
            r(jar, des)

def qp_restart():
    os.system("service qp_procmgr restart");


act={"-u":update,"-r":revert}

if __name__ == '__main__':
    with open(ws + jm, "r+") as f:
        manifest = [x.strip() for x in f.readlines()]
        patten = sys.argv[1] if len(sys.argv)>1 else "-u"
        f = act.get(patten,"-u")
        f(manifest)
    qp_restart()
