apiVersion: v1
kind: ConfigMap
metadata:
  name: nrfclient-kong-config
data:
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
  KONG_PROXY_LISTEN: '0.0.0.0:8000 http2, 0.0.0.0:8443 http2 ssl'  
  KONG_CASSANDRA_CONTACT_POINTS: cassandra-of-nrfclient-kong
  KONG_CASSANDRA_PORT: "9042"
  KONG_DATABASE: cassandra
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr