apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nrfclient-kong
    category: common
  name: nrfclient-kong
spec:
#  externalTrafficPolicy: Cluster
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
    - name: ssl-proxy
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
    - name: ssl-admin
      port: 8444
      targetPort: 8444
  selector:
    io.kompose.service: nrfclient-kong
  sessionAffinity: None
  type: ClusterIP
