apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nef-kong
    category: common
  name: nef-kong
spec:
  externalTrafficPolicy: Cluster
  {{if and (.Values.deploymentKongService.loadBalancerIP) (eq .Values.serviceKongService.type "LoadBalancer")}}
  loadBalancerIP: {{ .Values.deploymentKongService.loadBalancerIP }}
  {{end}}
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: ssl-proxy
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
    - name: ssl-admin
      port: 8444
      targetPort: 8444
  selector:
    io.kompose.service: nef-kong
  sessionAffinity: None
  type: {{ .Values.serviceKongService.type }}
