apiVersion: v1
kind: ServiceAccount
metadata:
  name: huyf
  namespace: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yugy
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hull
  namespace: kube-system
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding 
metadata: 
  name: admin-user
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: huyf
  namespace: kube-system
- kind: ServiceAccount
  name: yugy
  namespace: kube-system
- kind: ServiceAccount
  name: hull
  namespace: kube-system

